# Generated by Django 2.2.5 on 2020-06-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='destinamtion',
            field=models.CharField(default='Banglore', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(default='HUBLI', max_length=200),
        ),
    ]
