# Generated by Django 2.2.5 on 2020-06-08 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200608_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_dates',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='destinamtion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(max_length=200),
        ),
    ]
