# Generated by Django 2.2.5 on 2020-06-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200608_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='destinamtion',
            new_name='destination',
        ),
    ]
