# Generated by Django 2.2.5 on 2020-06-08 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200608_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_dates',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
